export const AUTH_SET_USER = '';

export const DRIVER_DOCUMENT_SET_ID = 'DRIVER_DOCUMENT_SET_ID';
export const DRIVER_DOCUMENT_SET_LICENCE = 'DRIVER_DOCUMENT_SET_LICENCE';
export const DRIVER_DOCUMENT_SET_AVATAR = 'DRIVER_DOCUMENT_SET_AVATAR';
export const DRIVER_DOCUMENT_SET_CAR_INSURANCE = 'DRIVER_DOCUMENT_SET_CAR_INSURANCE';
export const DRIVER_DOCUMENT_SET_VEHICLE = 'DRIVER_DOCUMENT_SET_VEHICLE';
export const DRIVER_DOCUMENT_RESET = 'DRIVER_DOCUMENT_RESET';

export const APP_SET_CURRENT_ORDER = 'APP_SET_CURRENT_ORDER'
export const APP_UPDATE_CURRENT_ORDER = 'APP_UPDATE_CURRENT_ORDER'
export const APP_SET_ORDERS = 'APP_SET_ORDERS'
export const APP_SET_CUSTOM_VALUES = 'APP_SET_CUSTOM_VALUES'

export const APP_LOCATION_SET_AVAILABLE = 'APP_LOCATION_SET_AVAILABLE'
export const APP_LOCATION_SET_CURRENT = 'APP_LOCATION_SET_CURRENT'

export const APP_ORDER_CHAT_SET_LIST = 'APP_ORDER_CHAT_SET_LIST'

export const APP_SET_FAQS = 'APP_SET_FAQS'
