const EventEmitter = require('events-async');
const ee = new EventEmitter();

module.exports = ee;

module.exports.EVENT_DRIVER_STATUS_CHANGED = 'EVENT_DRIVER_STATUS_CHANGED';

module.exports.EVENT_ORDER_CREATE = 'EVENT_ORDER_CREATE';
module.exports.EVENT_BUSINESS_UPDATE_ORDER = 'EVENT_BUSINESS_UPDATE_ORDER';
module.exports.EVENT_CUSTOMER_EMAIL_ASSIGN = 'EVENT_CUSTOMER_EMAIL_ASSIGN';
module.exports.EVENT_ORDER_RESCHEDULE = 'EVENT_ORDER_RESCHEDULE';
module.exports.EVENT_ORDER_SUGGESTION = 'EVENT_ORDER_SUGGESTION';
module.exports.EVENT_ORDER_STATUS_CHANGED = 'EVENT_ORDER_STATUS_CHANGED';
module.exports.EVENT_ORDER_DRIVER_ASSIGNED = 'EVENT_ORDER_DRIVER_ASSIGNED';
module.exports.EVENT_ORDER_DRIVER_REMOVE = 'EVENT_ORDER_DRIVER_REMOVE';
module.exports.EVENT_ORDER_PICKUP_ARRIVAL = 'EVENT_ORDER_PICKUP_ARRIVAL';
module.exports.EVENT_ORDER_PICKUP_COMPLETE = 'EVENT_ORDER_PICKUP_COMPLETE';
module.exports.EVENT_ORDER_DELIVERY_ARRIVAL = 'EVENT_ORDER_DELIVERY_ARRIVAL';
module.exports.EVENT_ORDER_DELIVERY_COMPLETE = 'EVENT_ORDER_DELIVERY_COMPLETE';
module.exports.EVENT_ORDER_RETURN_START = 'EVENT_ORDER_RETURN_START';
module.exports.EVENT_ORDER_RETURN_COMPLETE = 'EVENT_ORDER_RETURN_COMPLETE';
module.exports.EVENT_ORDER_CANCELED = 'EVENT_ORDER_CANCELED';
module.exports.EVENT_ORDER_COMPLETED = 'EVENT_ORDER_COMPLETED';
module.exports.EVENT_DRIVER_ALMOST_ARRIVE = 'EVENT_DRIVER_ALMOST_ARRIVE';

module.exports.EVENT_ORDER_PAYMENT_PRE_AUTHORIZE = 'EVENT_ORDER_PAYMENT_PRE_AUTHORIZE'
module.exports.EVENT_ORDER_PAYMENT_PRICE_CHANGE = 'EVENT_ORDER_PAYMENT_PRICE_CHANGE'
module.exports.EVENT_ORDER_PAYMENT_FINALIZE = 'EVENT_ORDER_PAYMENT_FINALIZE'
