export default {
  UPDATE_QUERY_PARAMS_USERS: 'UPDATE_QUERY_PARAMS_USERS',
  UPDATE_QUERY_PARAMS_ORDERS: 'UPDATE_QUERY_PARAMS_ORDERS',
  UPDATE_QUERY_PARAMS_CUSTOMERS: 'UPDATE_QUERY_PARAMS_CUSTOMERS',
  UPDATE_QUERY_PARAMS_INVOICES: 'UPDATE_QUERY_PARAMS_INVOICES',
  UPDATE_QUERY_PARAMS_CUSTOMER_ORDERS: 'UPDATE_QUERY_PARAMS_CUSTOMER_ORDERS',

  CUSTOMER_REQUESTED: 'CUSTOMER_REQUESTED',
  CUSTOMER_SUCCESS: 'CUSTOMER_SUCCESS',
  CUSTOMER_FAILED: 'CUSTOMER_FAILED',
  CUSTOMER_UPDATE_REQUESTED: 'CUSTOMER_UPDATE_REQUESTED',

  ORDER_REQUESTED: 'ORDER_REQUESTED',
  ORDER_SUCCESS: 'ORDER_SUCCESS',
  ORDER_FAILED: 'ORDER_FAILED',
  ORDER_UPDATE_REQUESTED: 'ORDER_UPDATE_REQUESTED',

  CANCEL_ORDER_REQUESTED: 'CANCEL_ORDER_REQUESTED',
  CANCEL_ORDER_SUCCESS: ' CANCEL_ORDER_SUCCESS',
  CANCEL_ORDER_FAILED: ' CANCEL_ORDER_FAILED',

  CUSTOMER_ORDER_REQUESTED: 'CUSTOMER_ORDER_REQUESTED',
  CUSTOMER_ORDER_SUCCESS: 'CUSTOMER_ORDER_SUCCESS',
  CUSTOMER_ORDER_FAILED: 'CUSTOMER_ORDER_FAILED',

  INVOICE_REQUESTED: 'INVOICE_REQUESTED',
  INVOICE_SUCCESS: 'INVOICE_SUCCESS',
  INVOICE_FAILED: 'INVOICE_FAILED',
  INVOICE_UPDATE_REQUESTED: 'INVOICE_UPDATE_REQUESTED',

  BUSINESS_INIT_REQUESTED: 'BUSINESS_INIT_REQUESTED',
  BUSINESS_INIT_SUCCESS: 'BUSINESS_INIT_SUCCESS',
  BUSINESS_INIT_FAILED: 'BUSINESS_INIT_FAILED'
}
