export default {
  UPDATE_QUERY_PARAMS_USERS: 'UPDATE_QUERY_PARAMS_USERS',
  UPDATE_QUERY_PARAMS_BANNERS: 'UPDATE_QUERY_PARAMS_BANNERS',
  UPDATE_QUERY_PARAMS_GROUPS: 'UPDATE_QUERY_PARAMS_GROUPS',
  UPDATE_QUERY_PARAMS_BUSINESS: 'UPDATE_QUERY_PARAMS_BUSINESS',
  UPDATE_QUERY_PARAMS_DRIVERS: 'UPDATE_QUERY_PARAMS_DRIVERS',
  UPDATE_QUERY_PARAMS_ORDERS: 'UPDATE_QUERY_PARAMS_ORDERS',
  UPDATE_QUERY_PARAMS_CUSTOMERS: 'UPDATE_QUERY_PARAMS_CUSTOMERS',
  UPDATE_QUERY_PARAMS_INVOICES: 'UPDATE_QUERY_PARAMS_INVOICES',
  UPDATE_QUERY_PARAMS_FAQS: 'UPDATE_QUERY_PARAMS_FAQS',
  UPDATE_QUERY_PARAMS_FAQCATS: 'UPDATE_QUERY_PARAMS_FAQCATS',
  UPDATE_QUERY_PARAMS_TRANSACTIONS: 'UPDATE_QUERY_PARAMS_TRANSACTIONS',
  UPDATE_QUERY_PARAMS_CUSTOMER_ORDERS: 'UPDATE_QUERY_PARAMS_CUSTOMER_ORDERS',
  UPDATE_QUERY_PARAMS_COMMENTS: 'UPDATE_QUERY_PARAMS_COMMENTS',
  UPDATE_QUERY_PARAMS_CUSTOMER_AVAILBLES:
    'UPDATE_QUERY_PARAMS_CUSTOMER_AVAILBLES',
  UPDATE_QUERY_PARAMS_CUSTOMER_TRANSACTIONS:
    'UPDATE_QUERY_PARAMS_CUSTOMER_TRANSACTIONS',
  UPDATE_QUERY_PARAMS_DRIVERS_ORDERS: 'UPDATE_QUERY_PARAMS_DRIVERS_ORDERS',
  UPDATE_QUERY_PARAMS: 'UPDATE_QUERY_PARAMS',
  UPDATE_QUERY_PARAMS_BUSINESS_CUSTOMERS:
    'UPDATE_QUERY_PARAMS_BUSINESS_CUSTOMERS',
  UPDATE_QUERY_PARAMS_BUSINESS_ORDERS: 'UPDATE_QUERY_PARAMS_BUSINESS_ORDERS',
  UPDATE_QUERY_PARAMS_BUSINESS_PAYMENTS:
    'UPDATE_QUERY_PARAMS_BUSINESS_PAYMENTS',
  UPDATE_QUERY_PARAMS_BUSINESS_INVOICES:
    'UPDATE_QUERY_PARAMS_BUSINESS_INVOICES',

  CUSTOMER_REQUESTED: 'CUSTOMER_REQUESTED',
  CUSTOMER_SUCCESS: 'CUSTOMER_SUCCESS',
  CUSTOMER_FAILED: 'CUSTOMER_FAILED',
  CUSTOMER_UPDATE_REQUESTED: 'CUSTOMER_UPDATE_REQUESTED',

  BUSINESS_REQUESTED: 'BUSINESS_REQUESTED',
  BUSINESS_SUCCESS: 'BUSINESS_SUCCESS',
  BUSINESS_FAILED: 'BUSINESS_FAILED',
  BUSINESS_UPDATE_REQUESTED: 'BUSINESS_UPDATE_REQUESTED',

  DRIVER_REQUESTED: 'DRIVER_REQUESTED',
  DRIVER_SUCCESS: 'DRIVER_SUCCESS',
  DRIVER_FAILED: 'DRIVER_FAILED',
  DRIVER_UPDATE_REQUESTED: 'DRIVER_UPDATE_REQUESTED',

  ORDER_REQUESTED: 'ORDER_REQUESTED',
  ORDER_SUCCESS: 'ORDER_SUCCESS',
  ORDER_FAILED: 'ORDER_FAILED',
  ORDER_UPDATE_REQUESTED: 'ORDER_UPDATE_REQUESTED',

  CANCEL_ORDER_REQUESTED: 'CANCEL_ORDER_REQUESTED',
  CANCEL_ORDER_SUCCESS: ' CANCEL_ORDER_SUCCESS',
  CANCEL_ORDER_FAILED: ' CANCEL_ORDER_FAILED',

  INVOICE_REQUESTED: 'INVOICE_REQUESTED',
  INVOICE_SUCCESS: 'INVOICE_SUCCESS',
  INVOICE_FAILED: 'INVOICE_FAILED',
  INVOICE_UPDATE_REQUESTED: 'INVOICE_UPDATE_REQUESTED',

  PAYMENT_REQUESTED: 'PAYMENT_REQUESTED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_UPDATE_REQUESTED: 'PAYMENT_UPDATE_REQUESTED',

  USER_REQUESTED: 'USER_REQUESTED',
  USER_SUCCESS: 'USER_SUCCESS',
  USER_FAILED: 'USER_FAILED',

  GROUP_REQUESTED: 'GROUP_REQUESTED',
  GROUP_SUCCESS: 'GROUP_SUCCESS',
  GROUP_FAILED: 'GROUP_FAILED',

  BANNER_REQUESTED: 'BANNER_REQUESTED',
  BANNER_SUCCESS: 'BANNER_SUCCESS',
  BANNER_FAILED: 'BANNER_FAILED',

  FAQCAT_REQUESTED: 'FAQCAT_REQUESTED',
  FAQCAT_SUCCESS: 'FAQCAT_SUCCESS',
  FAQCAT_FAILED: 'FAQCAT_FAILED',

  FAQCAT_DELETE: 'FAQCAT_DELETE',
  FAQCAT_DELETE_SUCCESS: 'FAQCAT_DELETE_SUCCESS',
  FAQCAT_DELETE_FAILED: 'FAQCAT_DELETE_FAILED',

  FAQ_REQUESTED: 'FAQ_REQUESTED',
  FAQ_SUCCESS: 'FAQ_SUCCESS',
  FAQ_FAILED: 'FAQ_FAILED',

  FAQ_DELETE: 'FAQ_DELETE',
  FAQ_DELETE_SUCCESS: 'FAQ_DELETE_SUCCESS'
}
